import type { OpencodeClient, UserMessage, Message } from "@opencode-ai/sdk";
import type { GodshotConfig } from "./config.js";
import type { PreimageStore } from "./storage.js";
import { buildDiffs, formatDiffSet, approxTokens } from "./diff.js";
import { curateHandoff } from "./curation.js";

/** Lightweight message wrapper for our purposes. */
type MsgEntry = {
  info: Message;
  parts: Array<unknown>;
};

/**
 * Build and execute a godshot handoff.
 *
 * 1. Fetch session messages to understand what was done.
 * 2. Get preimages and generate mechanical diffs.
 * 3. Fork the session at the last user message.
 * 4. Insert the handoff as a user-only message in the forked session.
 *
 * Returns a summary string to show in the current session.
 */
export async function executeGodshot(
  client: OpencodeClient,
  store: PreimageStore,
  config: GodshotConfig,
  sessionID: string,
  worktree: string,
  hint: string
): Promise<string> {
  // Fetch session messages for context
  let messages: MsgEntry[] = [];
  try {
    const result = await client.session.messages({ path: { id: sessionID } });
    if (result.data) {
      messages = result.data as MsgEntry[];
    }
  } catch {
    // Non-fatal: we can still generate diffs without message history
  }

  // Determine the last user message for forking
  let forkMessageID: string | undefined;
  const lastUserMsg = [...messages].reverse().find((m) => m.info.role === "user");
  if (lastUserMsg) {
    forkMessageID = lastUserMsg.info.id;
  }

  // Get preimages for this session
  const preimages = await store.getAllForSession(sessionID);

  // Generate diffs
  const diffSet = await buildDiffs(preimages, worktree, config.maxDiffTokens);

  // Attempt LLM curation for task metadata
  let curationText: string | null = null;
  try {
    curationText = await curateHandoff(client, config, messages, hint, diffSet);
  } catch {
    // Curation is best-effort; fall back to programmatic summary
  }

  // Build the handoff message
  const handoff = buildHandoffMessage(messages, config.model, hint, diffSet, curationText);

  // Fork the session
  let forkedSessionID: string | null = null;
  try {
    const forkResult = await client.session.fork({
      path: { id: sessionID },
      body: forkMessageID ? { messageID: forkMessageID } : undefined,
    });
    if (forkResult.data) {
      const session = forkResult.data;
      forkedSessionID = session.id;

      // Insert the handoff as a user message in the forked session
      // Use noReply to prevent the LLM from immediately responding
      await client.session.prompt({
        path: { id: forkedSessionID },
        body: {
          parts: [
            {
              type: "text",
              text: handoff,
            },
          ],
          noReply: true,
        },
      });

      // Auto-switch the TUI to the forked session
      // Uses the tui.publish method with a session select event,
      // which is supported by the OpenCode server (v2 SDK has a dedicated
      // selectSession method, but v1 publish endpoint also handles this event).
      try {
        await (client.tui as any).publish({
          body: {
            type: "tui.session.select",
            properties: { sessionID: forkedSessionID },
          },
        });
      } catch {
        // Non-critical: auto-switch is best-effort.
        // The forked session ID is still shown in the summary.
      }
    }
  } catch (err: any) {
    // Fork/prompt may fail; provide handoff inline instead
    return formatInlineHandoff(handoff, preimages.length, diffSet, err.message);
  }

  // Return summary for the current session
  return formatSummary(forkedSessionID, preimages.length, diffSet);
}

/**
 * Construct the handoff message that goes into the forked session.
 */
function buildHandoffMessage(
  messages: MsgEntry[],
  model: string,
  hint: string,
  diffSet: import("./diff.js").DiffSet,
  curationText?: string | null
): string {
  const lines: string[] = [];

  // ── Header ──
  lines.push(`# Godshot Handoff\n`);
  lines.push(
    `> **Ground-truth disclaimer:** The current filesystem is authoritative. The diffs below are provided as context only and may not reflect the full state of the codebase. Always verify against the actual files before making decisions.\n`
  );

  // ── LLM-curated task metadata (primary, at top) ──
  if (curationText) {
    lines.push(`## Task summary (LLM-curated)\n`);
    lines.push(curationText);
    lines.push("");
  }

  // ── Programmatic metadata (supplemental) ──
  lines.push(`## Task metadata\n`);
  lines.push(`- **Generated by**: godshot plugin using model \`${model}\``);
  lines.push(`- **Generated at**: ${new Date().toISOString()}`);
  if (hint) {
    lines.push(`- **Hint**: ${hint}`);
  }

  // Extract metadata from messages
  const userMessages = messages.filter((m) => m.info.role === "user");
  const assistantMessages = messages.filter((m) => m.info.role === "assistant");

  lines.push(`- **Conversation turns**: ${userMessages.length} user, ${assistantMessages.length} assistant`);

  if (userMessages.length > 0) {
    const lastUser = userMessages[userMessages.length - 1];
    const info = lastUser.info as UserMessage;
    const summary = info.summary;
    if (summary?.title) {
      lines.push(`- **Last task**: ${summary.title}`);
    }
    const lastUserText = extractTextFromParts(lastUser.parts);
    if (lastUserText) {
      const preview =
        lastUserText.length > 200
          ? lastUserText.slice(0, 200) + "..."
          : lastUserText;
      lines.push(`- **Last user message preview**: "${preview}"`);
    }
  }

  // Collect all user message summary info
  const allTitles = messages
    .filter((m) => {
      if (m.info.role !== "user") return false;
      const um = m.info as UserMessage;
      return um.summary?.title != null;
    })
    .map((m) => (m.info as UserMessage).summary!.title!);

  if (allTitles.length > 0) {
    lines.push(`- **Task history**:`);
    for (const title of allTitles.slice(-5)) {
      lines.push(`  - ${title}`);
    }
  }

  lines.push("");

  // ── Mechanical diffs ──
  lines.push(`## Mechanical diffs\n`);
  lines.push(
    `*Diffs generated from lazy first-touch preimages captured before files were first modified in this session. The current filesystem state is the ground truth.*\n`
  );
  if (diffSet.results.length === 0) {
    lines.push(`*(No file modifications were captured in this session.)*\n`);
  } else {
    lines.push(formatDiffSet(diffSet));
  }

  // ── Footer ──
  lines.push(`---\n`);
  lines.push(
    `*End of godshot handoff. The task is canonized. Use this context to continue work in a clean session.*\n`
  );

  return lines.join("\n");
}

/**
 * Extract visible text from message parts for preview purposes.
 */
function extractTextFromParts(parts: Array<unknown>): string {
  if (!Array.isArray(parts)) return "";

  const texts: string[] = [];
  for (const part of parts) {
    if (
      part &&
      typeof part === "object" &&
      "type" in part &&
      (part as any).type === "text" &&
      typeof (part as any).text === "string"
    ) {
      texts.push((part as any).text);
    }
  }
  return texts.join(" ").trim();
}

/**
 * Format the summary shown in the current session after godshot completes.
 */
function formatSummary(
  forkedSessionID: string | null,
  preimageCount: number,
  diffSet: import("./diff.js").DiffSet
): string {
  const lines: string[] = [];

  lines.push(`## Godshot complete\n`);

  if (forkedSessionID) {
    lines.push(`- **Forked session**: \`${forkedSessionID}\``);
  } else {
    lines.push(`- **Forked session**: *(fork not available — see handoff inline)*`);
  }

  lines.push(`- **Preimages captured**: ${preimageCount}`);
  lines.push(`- **Files in diff**: ${diffSet.results.length}`);

  const modifiedCount = diffSet.results.filter(
    (r) => r.kind === "diff" || r.kind === "new-file" || r.kind === "deleted"
  ).length;
  lines.push(`- **Modified files**: ${modifiedCount}`);

  if (diffSet.totalChars > 0) {
    lines.push(
      `- **Diff size**: ~${diffSet.totalChars.toLocaleString()} chars (~${approxTokens(diffSet.totalChars).toLocaleString()} tokens)`
    );
  }

  lines.push(
    `\nThe handoff has been placed in the forked session as a user-only message. Open that session to continue with clean context.`
  );

  return lines.join("\n");
}

/**
 * Fallback when fork fails: format the handoff inline in the current session.
 */
function formatInlineHandoff(
  handoff: string,
  preimageCount: number,
  diffSet: import("./diff.js").DiffSet,
  errorMsg: string
): string {
  const lines: string[] = [];

  lines.push(`## Godshot handoff (inline)\n`);
  lines.push(
    `> **Note:** Session fork failed (${errorMsg}). The handoff is provided inline below instead.\n`
  );
  lines.push(`- **Preimages captured**: ${preimageCount}`);
  lines.push(`- **Files in diff**: ${diffSet.results.length}\n`);
  lines.push(`---\n`);
  lines.push(handoff);

  return lines.join("\n");
}
